### ISSUE TITLE
Export toRawSVG dose not working correctly

### ISSUE THREAD

**Issue by AbdullahSh-25** [4Q-s-r-o/signature#87] opened 2023-02-25 12:25 UTC
1. I draw separated paths in signature widget
2. when use toRawSVG it shown as one path
 
before
![photo_2023-02-25_15-24-15](https://user-images.githubusercontent.com/101022174/221356650-b7265fc3-5ae1-48e0-9436-e1051575689b.jpg)

after
![photo_2023-02-25_15-24-20](https://user-images.githubusercontent.com/101022174/221356656-097b029d-515e-48f6-a67c-3360d11bd8fe.jpg)

**Comment by tonyhart7** [comment] 2023-04-09 23:51
Yeah its sucks

**Comment by MartinHlavna** [comment] 2023-05-24 14:40
@h7x4  you have implemented svg export and have more insight here.  I think the problem is not generating spaces between polylines. Solution would be to check for gaps between points, but you may have better idea.

**Comment by h7x4** [comment] 2023-06-01 11:47
This is a bug with the way the export function uses the list of actions (`_latestActions`). I assumed that the list would be `[ 1st stroke, 2nd stroke, 3rd stroke ]`, but it turns out that it is saved as `[ 1st stroke, 1st and 2nd stroke, 1st 2nd and 3rd stroke ]`, which causes the SVG to draw overlapping lines.

I'll see if I can make a fix in the upcoming days.

**Comment by AbdullahSh-25** [comment] 2023-06-01 12:13
yes that true i figured out that 
i fixed it like this way

`    final List<List<Point>> list = [];

    for (int i = 0; i < _latestActions.length; i++) {
      final int val;
      final List<Point> points = [];
      if (i == 0) {
        val = 0;
      } else {
        val = _latestActions[i - 1].length;
      }
      for (int j = val; j < _latestActions[i].length; j++) {
        points.add(_latestActions[i][j]);
      }
      list.add(points);
    }`

and when creating `polylines` string i used this list

it is not the best way but it fix the problem

**Comment by h7x4** [comment] 2023-06-01 13:03
I think the whole underlying data structure should be swapped out with a list of stroke objects in the first place. We are currently using $\mathcal{O}(n^2)$ space to store history, and even if we only fixed that part, we would either have to store everything doubly and allow for the possibility of inconsistent data, or do some finicky list indexing which kinda just unravels parts of the abstraction layer of storing stroke objects in the first place.

See https://github.com/4Q-s-r-o/signature/issues/73#issuecomment-1304297677, just without the part about each stroke having a color.

Do you have any thoughts @MartinHlavna, before I start working on it?

**Comment by henry2man** [comment] 2023-07-26 06:50
I can confirm that #91 works better than current pub version, except in terms of color conversion (please see https://github.com/4Q-s-r-o/signature/pull/91#issuecomment-1651080671).

**Comment by MartinHlavna** [comment] 2023-11-23 14:37
Sorry I had to focus on different project for some time. I will review and hopefully merge #91  soon.

@h7x4 I agree that some refactoring of data storage is spot on. Some parts of the plugin since first version of plugin.

**Comment by MartinHlavna** [comment] 2024-05-07 14:37
#91 has been already merged and released. I will close this.

**Closed as completed by MartinHlavna** 2024-05-07 14:37 UTC
Labels: waiting-for-response
