### ISSUE TITLE
A strange dot at onPointerUp

### ISSUE THREAD

**Issue by RegisMelgaco** [4Q-s-r-o/signature#31] opened 2020-10-09 10:44 UTC
It doesn't looks right to me leaving a dot at the and of every pointer up. I don't now why the signature was implemented this way, but i think it would be useful if the user (dev) want it or not. Sorry if i'm not clear, this is my first issue on open source.
<img width="837" alt="Screen Shot 2020-10-09 at 07 36 23" src="https://user-images.githubusercontent.com/26839952/95573647-244a6600-0a02-11eb-8258-1188b9f317e5.png">

**Comment by ethael** [comment] 2021-02-22 07:11
Hello, does the library example do the same for you? Because we are not able to reproduce this state.

**Comment by MartinHlavna** [comment] 2021-02-23 15:16
I was able to reproduce this. The problem was that last point is drawn as point (since the is no other point we can draw line to) but it was ignoring the pen stroke width for radius. This needs to be "half-width" to ensure it blends with the line.

Fix will be released in next version both for stable and pre-release.

**Closed as completed by MartinHlavna** 2021-02-23 15:16 UTC

**Comment by RegisMelgaco** [comment] 2021-02-23 22:57
Thanks man!
