### ISSUE TITLE
toPngBytes() always return 400x500 px image

### ISSUE THREAD

**Issue by antiv** [4Q-s-r-o/signature#71] opened 2022-10-20 10:45 UTC
Hi,

after upgrading to 5.2.1 all my signatures are saved as 400x500px and cannot be resized.

I find this part of code:

``` 
//WIDTH AND HEIGHT IS OPTIONAL. IMAGE WILL BE CENTERED
 final ui.Image? image = await toImage(height: 500, width: 400);
```

How can I use toPngBytes() to get an image in the proper size, based on image data?
In old version that part works fine.

**Comment by alexlovar** [comment] 2022-11-01 22:52
Hi, did you find a solution?

**Comment by antiv** [comment] 2022-11-02 09:56
HI, not really. I switched back to the old version

**Comment by MartinHlavna** [comment] 2022-11-03 08:25
This is bug of course. It was intended to take defaultWidth and defaultHeight. Solution with optional parameters for toPngBytes is better though. Will be fixed soon.

**Comment by MartinHlavna** [comment] 2022-11-03 08:27
Closing this ticket in favor of #68 since the root cause is same.

**Closed as completed by MartinHlavna** 2022-11-03 08:27 UTC
